export const defaultCarouselConfiguration = {
	autoPlay: false,
	dynamicHeight: true,
	centerSlidePercentage: 100,
	showArrows: true,
	showStatus: false,
	showIndicators: true,
	showThumbs: false,
	infiniteLoop: false,
	selectedItem: 0,
	axis: 'horizontal',
	useKeyboardArrows: true,
	stopOnHover: true,
	interval: 5000,
	transitionTime: 350,
	swipeable: true,
	emulateTouch: true,
	centerMode: false,
};